Let's do self review
hydaline-code/Project_review pull request #1
Opened 2023-01-23 09:29 UTC by hydaline-code

Hello in this request I am playing the role of the reviewer so as to learn how to typically write my code in a professional way.Let me review it now and comment.

2023-01-23 09:56 UTC, hydaline-code reviewed
Hello well done till now but kindly go through the review and update your code . If you are not understanding a review as supposed to be kindly reach out for further explanation.Thanks

2023-01-23 09:56 UTC, hydaline-code commented on README.md
> +> Describe 1 - 3 features you will add to the project.
Hello good readme presentation but kindly add and describe the features you odd to work on

2023-01-23 09:56 UTC, hydaline-code commented on index.html
> +      <p>Handcrafted, home-made masterpieces</p>
Good use of p-tags but you should use a heading most preferably

2023-01-23 09:56 UTC, hydaline-code commented on index.html
> +    <div class="container">
hey you cann't use a div before a section because a section is semantically higher than the div please do a check on that

2023-01-23 09:56 UTC, hydaline-code commented on index.html
> +            <h2>Premium Materials</h2>
kindly follow the order of headings form h1-h2....etc

2023-01-23 09:56 UTC, hydaline-code commented on index.html
> +          <div class="icon"><i class="fa fa-3x fa-truck"></i></div>
Good use of imported icons

2023-01-23 09:56 UTC, hydaline-code commented on index.html
> +          <h2>$600</h2>
Please checkout if this is not a figure caption instead.

2023-01-23 10:19 UTC, OyePriscilla requested changes
Hi @hydaline-code 😃 , 

Good job so far!

There are some issues that you still need to work on to go to the next project but you are almost there!

![so-close](https://user-images.githubusercontent.com/103386183/196423863-0f522555-1b03-455e-a452-b822cdcfc398.gif)

## Highlights
✔️ Good use inline comments 👍
✔️ Good use summary template 👍

## Required Changes ♻️

## Optional suggestions

- [optional] **It will be more human-friendly to use a couple of emojis and/or gifs in the review.**


_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-23 10:19 UTC, OyePriscilla commented on index.html
> +      <p>Handcrafted, home-made masterpieces</p>
- [ ] Awesome observation! can you please rephrase your comment politely as a suggestion 💁‍♂️ and provide elaborate reason(s) for the required changes? It may be obvious to you and not so for others. 👍

2023-01-23 10:19 UTC, OyePriscilla commented on index.html
> +            <h2>Premium Materials</h2>
- [ ] Awesome observation! can you please state the reason(s) for the required changes? It may be obvious to you and not so for others. 👍

2023-01-23 10:19 UTC, OyePriscilla commented on index.html
> +          <h2>$600</h2>
Awesome observation! Please rephrase your comment in a way that the other person will understand you easily? It may be obvious to you and not so for others. 👍

2023-01-23 12:03 UTC, hydaline-code commented on style.css
> +footer > ul {
Hey good use of targetting child selectors I kindly invited you to be coherent in your code because footer > <ul> >li can not be seen before footer > <ul> so I suggest you change the order of appearance for code efficiency.Thanks

2023-01-23 12:45 UTC, Lizdev-05 requested changes
Hi @hydaline-code, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't been addressed yet.

<img src="https://media2.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-23 12:45 UTC, Lizdev-05 commented on index.html
> +      <p>Handcrafted, home-made masterpieces</p>
- [OPTIONAL] Great work implementing the changes requested by the previous reviewer 👍. To give more explanation about why the writer should use `h` tag instead of the title, you can also explain that 

> Header tags improve the readability and SEO of a webpage

2023-01-23 12:45 UTC, Lizdev-05 commented on index.html
> +    <div class="container">
- [OPTIONAL] I think it will be well received if you use a more polite tone instead of 'hey' 😊 . Some students might find it offensive.

2023-01-23 12:45 UTC, Lizdev-05 commented on index.html
> +            <h2>Premium Materials</h2>
Kindly add the reason for why you are requesting changes as required by the previous reviewer, it will make the student understand why the suggested changes are necessary. 😊

2023-01-23 12:45 UTC, Lizdev-05 commented on index.html
> +          <div class="icon"><i class="fa fa-3x fa-truck"></i></div>
Great work commending the programmer 😊 👍

2023-01-23 12:45 UTC, Lizdev-05 commented on index.html
> +          <h2>$600</h2>
[OPTIONAL] I think it will be well received if you use a more polite tone instead of 'hey' 😊 . Some students might find it offensive.

2023-01-24 16:44 UTC, hydaline-code commented on index.html
> +    <div class="container">
Kindly change the position of the div due to the semantics hierarchy. A section is semantically higher than a div.

2023-01-24 16:44 UTC, hydaline-code commented on index.html
> +            <h2>Premium Materials</h2>
kindly follow the order of stating the heading because they follow a certain hierarchy of presentation. for instance, the h1-tags best describe the main topic (the most pertinent information), and the others are for subheadings.

2023-01-24 16:44 UTC, hydaline-code commented on style.css
> +  width: 100%;
kindly check the use of width and max-width seems to be a repetition for one width is contained in the other. please I suggest you either specify the width or use the max-width. Also, the mixup of units is not really an efficient way to code kindly rely on one unit and apply it well. thanks

2023-01-24 16:44 UTC, hydaline-code commented on style.css
> +footer > ul {
You've made good use of targeting child selectors I kindly invite you to be coherent in your code because 
footer > ul > li can not be seen before footer > ul so I suggest you please change the order of appearance for code efficiency. Thanks

2023-01-25 05:45 UTC, merged